[build]
  base = ""
  publish = "."
  command = "echo 'Deploying static site'"

[context.deploy-preview]
  command = "echo 'Deploying static site preview'"

[context.branch-deploy]
  command = "npm run build"
